# Generated by Django 4.1.5 on 2023-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Your answer has been submitted.', max_length=10000),
        ),
    ]
